
Feature('Volos', /*{retries: 2}*/);

Scenario('test Volos', (I) => {
  I.retry({ retries: 2, minTimeout: 1000 }).click('ALLOW');
  I.retry({ retries: 2, minTimeout: 1000 }).click('BEGIN');
  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Email', 'a.koscynich@mygento.ru');
  I.retry({ retries: 2, minTimeout: 1000 }).click('NEXT');
  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Password', 'feq0ZYIc__');
  I.retry({ retries: 2, minTimeout: 1000 }).click('SUBMIT');
  I.retry({ retries: 2, minTimeout: 1000 }).click('Общий чат');
  //pause();
  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
  I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');

  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
  I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');

    I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
    I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
      I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
      I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
        I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
        I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
          I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
          I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
            I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
            I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
              I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
              I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                  I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                    I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                    I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                      I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                      I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                        I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                        I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                          I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                          I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                            I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                            I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                              I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                              I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                  I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                    I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                    I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                      I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                      I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                        I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                        I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                          I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                          I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                            I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                            I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                              I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                              I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                  I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                  I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                    I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                    I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                      I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                      I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                        I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                        I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                          I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                          I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                            I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                            I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
                                                              I.retry({ retries: 2, minTimeout: 1000 }).fillField('Say something', '@MikhailVolos --');
                                                              I.retry({ retries: 2, minTimeout: 1000 }).click('SEND');
  //I.screenshot();
  });
//
