
Feature('CANON', {retries: 1});

Scenario('test links', (I) => {
  I.amOnPage('https://store.canon.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Больше новостей и акций');
  //I.saveScreenshot('CANON_main.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('ФОТОАППАРАТЫ');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="ui-id-3"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Новинки');
  //I.saveScreenshot('CANON_menu.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="ui-id-11"]');
  I.retry({ retries: 10, minTimeout: 1000 }).seeInSource('"page-title-wrapper">Новинки');
  //I.saveScreenshot('CANON_catalog.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/div/div/div[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.links"]/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход для клиентов');
  //I.saveScreenshot('CANON_login.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="maincontent"]/div[4]/div/div[2]/div[2]/div[2]/div/div/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Создать новый аккаунт');
  //I.saveScreenshot('CANON_registration.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="header-right"]/div[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('У Вас нет товаров в корзине.');
  //I.saveScreenshot('CANON_emptyCart.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[1]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Компания Canon - мировой лидер');
  //I.saveScreenshot('CANON_about.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Выбрать товар в интернет-магазине ');
  //I.saveScreenshot('CANON_kak-kupit.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[3]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Основные понятия');
  //I.saveScreenshot('CANON_soglashenie.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[4]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Настоящая Политика');
  //I.saveScreenshot('CANON_politika.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[5]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Изготовитель предоставляет');
  //I.saveScreenshot('CANON_pravila.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[6]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Интернет-магазин');
  //I.saveScreenshot('CANON_questions.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[7]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Уважаемые покупатели,');
  //I.saveScreenshot('CANON_dostavka.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[8]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Возврат товара надлежащего качества');
  //I.saveScreenshot('CANON_vozvrat.png');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/footer/div/div[2]/ul/li[9]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('АДРЕС ОФИСА');
  //I.saveScreenshot('CANON_kontakty.png');
});

Scenario('test login', (I) => {
  I.amOnPage('https://store.canon.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/div/div/div[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.links"]/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход для клиентов');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Это обязательное поле.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="email"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="pass"]', "feq0Z");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Введите действительный адрес');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="email"]', "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="pass"]', "feq0Z");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вы ввели неверные данные');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="email"]', "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="pass"]', "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/div/div/div[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.links"]/ul/li[2]/div/ul/li[1]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Личный кабинет');
  //I.saveScreenshot('CANON_account.png');
});

Scenario('test order', (I) => {
  I.amOnPage('https://store.canon.ru/fotobumaga-plus-glossy-ii-pp-201-4h6-10h15-sm-50-listov.html');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="qty"]', ' ');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="product-addtocart-button"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Введите, пожалуйста, действительно число в этом поле.");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="qty"]', '1');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="product-addtocart-button"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("в Вашу корзину.");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="header-right"]/div[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="minicart-content-wrapper"]/div[2]/div[5]/div/a');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", ' ');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Это обязательное поле.");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty mage-error']", '0');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Пожалуйста, введите число больше 0 в этом поле.");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty mage-error']", '0.1');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Самое меньшее, что вы можете купить, это 1.");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", '999');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("нет в таком количестве на складе.");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", '9999');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Самое большее, что вы можете купить, это1000.");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="discount-coupon-form"]/div/div[2]/div/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Это обязательное поле.");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="coupon_code"]', '9999');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="discount-coupon-form"]/div/div[2]/div/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Код купона");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", '1');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div[2]/button[2]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="maincontent"]/div[4]/div/div[2]/div[1]/ul/li[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see("ОФОРМЛЕНИЕ ЗАКАЗА");
  //I.saveScreenshot('CANON_order.png');
});

Scenario('test registration', (I) => {
  I.amOnPage('https://store.canon.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/div/div/div[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.links"]/ul/li[3]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Создать новый аккаунт');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="canon-agreement-checkbox"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="canon-fz-checkbox"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Это обязательное поле.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="firstname"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="lastname"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="email_address"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="password"]', "feq");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="password-confirmation"]', "fe");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="captcha_user_create"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Введите действительный адрес ');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Минимальная длина');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Введите одно и тоже значение');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="firstname"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="lastname"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="email_address"]', "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="password"]', "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="password-confirmation"]', "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="captcha_user_create"]', "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вы уже зарегистрированы');
});

Scenario('test search', (I) => {
  I.amOnPage('https://store.canon.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="popup-search-button"]/div');
  I.fillField('//*[@id="search"]', 'фото');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="search_mini_form"]/div[2]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see("Результаты поиска для: 'фото'");
  //I.saveScreenshot('CANON_search_results.png');
});

Scenario('test wishlist', (I) => {
  I.amOnPage('https://store.canon.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/div/div/div[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.links"]/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход для клиентов');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="email"]', "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="pass"]', "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="nav-toggle"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('/html/body/div[1]/div/div/div[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.links"]/ul/li[2]/div/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Мое избранное');
  //I.saveScreenshot('CANON_whishlist.png');
});
