

Feature('ELC', /*{retries: 3}*/);

Scenario('test links', (I) => {
  I.amOnPage('https://www.elc-russia.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="page"]/div/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Бренды');
  I.see('Вступить в клуб');
  I.see('Задать вопрос');
  I.see('Войти');
  I.see('Регистрация');
  I.see('Новинки');
  I.see('Магазины');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="menu"]/div[2]/a[3]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="titleOpenReview"]');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[9]/div/div[2]/ul/li[1]/div/ul/li[1]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Доставка осуществляется по территории России.');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="titleOpenReview"]');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[9]/div/div[2]/ul/li[1]/div/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Возврат товара в интернет-магазин Elc-russia.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="titleOpenReview"]');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[9]/div/div[2]/ul/li[1]/div/ul/li[3]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Публичная оферта');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="titleOpenReview"]');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[9]/div/div[2]/ul/li[1]/div/ul/li[5]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Карта сайта');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="titleOpenReview"]');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[9]/div/div[2]/ul/li[1]/div/ul/li[6]/a');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).see('Зайти через учетную запись OpenID');
});

Scenario('test login', (I) => {
  I.amOnPage('https://www.elc-russia.ru/customer/account/login/');
  I.retry({ retries: 3, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 3, minTimeout: 1000 }).see('Это поле обязательно для заполнения.');
  I.retry({ retries: 5, minTimeout: 1000 }).fillField('//*[@id="email"]', 'tolik_kosmail.ru');
  I.retry({ retries: 3, minTimeout: 1000 }).fillField('//*[@id="pass"]', 'feq0Z');
  I.retry({ retries: 3, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 3, minTimeout: 1000 }).see('Пожалуйста, введите правильный адрес электронной почты. Например johndoe@domain.com.');
  I.retry({ retries: 3, minTimeout: 1000 }).see('Please enter 6 or more characters without leading or trailing spaces.');
  I.retry({ retries: 5, minTimeout: 1000 }).fillField('//*[@id="email"]', 'tolik_kos@mail.ru');
  I.retry({ retries: 3, minTimeout: 1000 }).fillField('//*[@id="pass"]', 'feq0ZYI');
  I.retry({ retries: 3, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 3, minTimeout: 1000 }).see('Неправильный логин или пароль.');
  I.retry({ retries: 5, minTimeout: 1000 }).fillField('//*[@id="email"]', 'tolik_kos@mail.ru');
  I.retry({ retries: 3, minTimeout: 1000 }).fillField('//*[@id="pass"]', 'feq0ZYIc');
  I.retry({ retries: 3, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 3, minTimeout: 1000 }).see('Мой аккаунт');
});

Scenario('test registration', (I) => {
  I.amOnPage('https://www.elc-russia.ru/');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[1]/div[2]/a[2]/i');
  I.wait(1);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="modal_auth"]/div/div[2]/div[3]/div/div/button');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-register"]/div[5]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Это поле обязательно для заполнения');
  I.fillField('//*[@id="firstname"]', 'Test');
  I.fillField('//*[@id="lastname"]', 'Account');
  I.fillField('//*[@id="email_address"]', 'tolik_kosmail.ru');
  I.fillField('//*[@id="password"]', 'f');
  I.fillField('//*[@id="confirmation"]', 'fe');
  I.click('//*[@id="terms-input"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-register"]/div[5]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Please');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Пожалуйста');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Пожалуйста, введите');
});

Scenario('test search', (I) => {
  I.amOnPage('https://www.elc-russia.ru/');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="mm-0"]/div[1]/div[2]/a[1]/i');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="search"]', 'lego');
  I.click('//*[@id="simple_search_submit"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Результаты по запросу «lego»');
  I.see('LEGO');
});

Scenario('screenshots', (I) => {
I.amOnPage('https://www.elc-russia.ru/');
I.saveScreenshot('ELC_main.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_main.png');
I.amOnPage('https://www.elc-russia.ru/store-locator');
I.saveScreenshot('ELC_store-locator.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_store-locator.png');
I.amOnPage('https://www.elc-russia.ru/delivery/');
I.saveScreenshot('ELC_delivery.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_delivery.png');
I.amOnPage('https://www.elc-russia.ru/trackorder/');
I.saveScreenshot('ELC_trackorder.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_trackorder.png');
I.amOnPage('https://www.elc-russia.ru/careers');
I.saveScreenshot('ELC_careers.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_careers.png');
I.amOnPage('https://www.elc-russia.ru/rental');
I.saveScreenshot('ELC_rental.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_rental.png');
I.amOnPage('https://www.elc-russia.ru/#modal_auth');
I.saveScreenshot('ELC_login.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_login.png');
I.amOnPage('https://www.elc-russia.ru/customer/account/login/');
I.saveScreenshot('ELC_registration.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_registration.png');
I.amOnPage('https://www.elc-russia.ru/returns');
I.saveScreenshot('ELC_returns.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_returns.png');
I.amOnPage('https://www.elc-russia.ru/terms');
I.saveScreenshot('ELC_terms.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_terms.png');
I.amOnPage('https://www.elc-russia.ru/catalog/seo_sitemap/category/');
I.saveScreenshot('ELC_sitemap.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_sitemap.png');
I.amOnPage('https://www.elc-russia.ru/privacy-policy');
I.saveScreenshot('ELC_privacy-policy.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_privacy-policy.png');
I.amOnPage('https://www.elc-russia.ru/disclamer');
I.saveScreenshot('ELC_disclamer.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_disclamer.png');
I.amOnPage('https://www.elc-russia.ru/partnership');
I.saveScreenshot('ELC_partnership.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_partnership.png');
I.amOnPage('https://www.elc-russia.ru/blog/');
I.saveScreenshot('ELC_blog.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_blog.png');
I.amOnPage('https://www.elc-russia.ru/about-us');
I.saveScreenshot('ELC_about.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_about.png');
I.amOnPage('https://www.elc-russia.ru/corporate_clients');
I.saveScreenshot('ELC_corporate_clients.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_corporate_clients.png');
I.amOnPage('https://www.elc-russia.ru/elc-birthday-club-terms');
I.saveScreenshot('ELC_birthday-club.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_birthday-club.png');
I.amOnPage('https://www.elc-russia.ru/pcorp');
I.saveScreenshot('ELC_pcorp.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_pcorp.png');
I.amOnPage('https://www.elc-russia.ru/articles');
I.saveScreenshot('ELC_articles.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_articles.png');
I.amOnPage('https://www.elc-russia.ru/contacts/');
I.saveScreenshot('ELC_contacts.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_contacts.png');
I.amOnPage('https://www.elc-russia.ru/konstruktory.html');
I.saveScreenshot('ELC_cataog.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/ELC_cataog.png');
});
