
Feature('MET', /*{retries: 2}*/);

Scenario('test links', (I) => {
  I.amOnPage('https://metpromko.ru/');
  I.click('//*[@id="cities-popup"]/div/div/span');
  I.see('Оформить заказ');
  I.amOnPage('https://metpromko.ru/onepagecheckout/');
  I.see('КОРЗИНА ПУСТА');
  I.amOnPage('https://metpromko.ru/about/');
  I.see('О КОМПАНИИ');
  I.amOnPage('https://metpromko.ru/contacts/');
  I.see('Внимание! Компания Метпромко');
  I.amOnPage('https://metpromko.ru/dostavka/');
  I.see('Компания Метпромко доставляет');
  I.amOnPage('https://metpromko.ru/oplata/');
  I.seeInSource('"std">Оплата');
  I.amOnPage('https://metpromko.ru/uslugi/');
  I.see('Компания Метпромко является');
  I.click('//*[@id="menu-icon"]');
  I.see('Металлопрокат');
  I.see('Труба');
  I.see('Лист');
});

Scenario('test login', (I) => {
  I.amOnPage('https://metpromko.ru/');
  I.click('//*[@id="cities-popup"]/div/div/span');
  I.amOnPage('https://metpromko.ru/customer/account/login/');
  I.see('СТРАНИЦА АВТОРИЗАЦИИ');
  I.click('//*[@id="send2"]');
  I.see('Это поле обязательно для заполнения.');
  I.fillField("input[name='login[username]']", "tolik_kos@ail.ru");
  I.fillField("input[name='login[password]']", "feq");
  I.click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Please enter 6 or more characters without leading or trailing spaces.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[name='login[username]']", "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[name='login[password]']", "feq0ZYI");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Неверный адрес электронной почты (email) или пароль.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[name='login[username]']", "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[name='login[password]']", "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Выйти');
  I.see('Моя учётная запись');
  });

  Scenario('test registration', (I) => {
    I.amOnPage('https://metpromko.ru/');
    I.click('//*[@id="cities-popup"]/div/div/span');
    I.amOnPage('https://metpromko.ru/customer/account/login/');
    I.see('СТРАНИЦА АВТОРИЗАЦИИ');
    I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="login-form"]/div/div/div[2]/div/div/div/button');
    I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="header-account"]/div[2]/div/div/div[4]/div/button');
    I.retry({ retries: 10, minTimeout: 1000 }).see('First name is required!');
    I.retry({ retries: 10, minTimeout: 1000 }).see('Last name is required!');
    I.retry({ retries: 10, minTimeout: 1000 }).see('Email address is required!');
    I.retry({ retries: 10, minTimeout: 1000 }).see('Password is required!');
    I.retry({ retries: 10, minTimeout: 1000 }).see('Terms and Conditions are required!');
    I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="youama-firstname"]','111');
    I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="youama-lastname"]','111');
    I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="header-account"]/div[2]/div/div/div[4]/div/button');
    });

    Scenario('screenshots', (I) => {
      I.amOnPage('https://metpromko.ru/');
      I.click('//*[@id="cities-popup"]/div/div/span');
      I.wait(1);
      I.saveScreenshot('MET_main.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_main.png');
      I.amOnPage('https://metpromko.ru/checkout/cart/');
      I.saveScreenshot('MET_checkout.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_checkout.png');
      I.amOnPage('https://metpromko.ru/contacts');
      I.saveScreenshot('MET_contacts.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_contacts.png');
      I.amOnPage('https://metpromko.ru/about/');
      I.saveScreenshot('MET_about.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_about.png');
      I.amOnPage('https://metpromko.ru/dostavka/');
      I.saveScreenshot('MET_dostavka.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_dostavka.png');
      I.amOnPage('https://metpromko.ru/oplata/');
      I.saveScreenshot('MET_oplata.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_oplata.png');
      I.amOnPage('https://metpromko.ru/uslugi/');
      I.saveScreenshot('MET_uslugi.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_uslugi.png');
      I.amOnPage('https://metpromko.ru/customer/account/login/');
      I.saveScreenshot('MET_login.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_login.png');
      I.click('//*[@id="login-form"]/div/div/div[2]/div/div/div/button');
      I.wait(1);
      I.saveScreenshot('MET_registration.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_registration.png');
      I.amOnPage('https://metpromko.ru/metalloprokat');
      I.wait(4);
      I.saveScreenshot('MET_catalog.png');
      I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MET_catalog.png');
});
