
Feature('MID');

Scenario('test compare', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.menu"]/div/div/nav/ul/li[1]/a[1]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="maincontent"]/div[3]/div[1]/div[4]/ol/li[1]/div/div/div[2]/a/span/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.Product__Actions--Bookmark > div > div > a.action.tocompare');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вы добавили товар');
});

Scenario('test links', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.click('li.authorization-link > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход в систему');
  I.click('div.top-right.mobile-center > div > div > div > ul > li:nth-child(2) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Создать новую учётную запись клиента');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Встраиваемая Бытовая Техника');
  I.click('nav > ul > li:nth-child(5) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Бесплатная доставка по всей России');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('nav > ul > li:nth-child(6) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Поиск сервисного центра');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('nav > ul > li:nth-child(7) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Midea – мировой производитель бытовой техники');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('nav > ul > li:nth-child(8) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Midea в Российской Федерации');
  I.click('//*[@id="cms-static-main-footer"]/div[2]/div/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="cms-static-main-footer"]/div[2]/div/div/ul[1]/li[1]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Midea – мировой производитель бытовой техники');
  I.click('//*[@id="cms-static-main-footer"]/div[2]/div/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="cms-static-main-footer"]/div[2]/div/div/ul[1]/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Блог');
  I.click('//*[@id="cms-static-main-footer"]/div[2]/div/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="cms-static-main-footer"]/div[2]/div/div/ul[1]/li[3]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Midea в Российской Федерации');
  I.click('//*[@id="cms-static-main-footer"]/div[3]/div/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="cms-static-main-footer"]/div[3]/div/div/ul/li[1]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Политика конфиденциальности');
  I.click('//*[@id="cms-static-main-footer"]/div[3]/div/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="cms-static-main-footer"]/div[3]/div/div/ul/li[2]/a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Договор оферты');
});

Scenario('test login', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.click('li.authorization-link > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход в систему');
  I.click('//*[@id="send2"]');
  I.see('Это поле обязательно для заполнения.');
  I.fillField("input[name='login[username]']", "tolik_kosmal.ru");
  I.fillField("input[name='login[password]']", "feq0ZYIc");
  I.click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Пожалуйста, введите правильный адрес электронной почты (Пример: johndoe@domain.com).');
  I.fillField("input[name='login[username]']", "tolik_kos@mail.ru");
  I.fillField("input[name='login[password]']", "feq0ZYI");
  I.click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('неправильный адрес электронной почты (email) или пароль.');
  I.fillField("input[name='login[username]']", "tolik_kos@mail.ru");
  I.fillField("input[name='login[password]']", "feq0ZYIc");
  I.click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Моя панель управления');
});

Scenario('test order', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.menu"]/div/div/nav/ul/li[1]/a[1]');
  I.wait(8);
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="maincontent"]/div[3]/div[1]/div[4]/ol/li[1]/div/div/div[3]/div[4]/div/div[2]/form/button');
  I.wait(8);
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.righ-header-content.col-lg-3.col-md-3.col-sm-3.col-xs-12 > div.minicart-wrapper > a.action.icon.icon-shopping-bag.showcart');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", "0");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).retry({ retries: 10, minTimeout: 1000 }).see('Пожалуйста, введите в это поле число больше 0.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty mage-error']", "0.1");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вы не можете приобрести меньше, чем 1.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", "0.1");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вы не можете приобрести меньше, чем 1.');
  I.retry({ retries: 10, minTimeout: 1000 }).clearField("input[class='input-text qty']");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Это поле обязательно для заполнения.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty mage-error']", "9999");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('У нас нет столько товара');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", "99999");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вы не можете приобрести больше, чем 10000.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("input[class='input-text qty']", "1");
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.cart.main.actions > button');
  I.retry({ retries: 10, minTimeout: 1000 }).click('li:nth-child(1) > button');
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.checkout-payment-method.submit > div > div > button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('No payment method selected');
});

Scenario('test registration', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.top-right.mobile-center > div > div > div > ul > li:nth-child(2) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Создать новую учётную запись клиента');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="newsletter"]', "1");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="newsletter"]', "1");
  I.retry({ retries: 10, minTimeout: 1000 }).see('Это поле обязательно для заполнения.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='email_address']", "tolik_kosmal.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='password']", "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='firstname']", "Test");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='lastname']", "Account");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='password-confirmation']", "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Пожалуйста, введите правильный адрес электронной почты (Пример: johndoe@domain.com).');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='email_address']", "tolik_kos@mail.ru");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="newsletter"]', "1");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Учётная запись с таким адресом электронной почты уже существует.');
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='password']", "feq");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField("//*[@id='password-confirmation']", "feq0ZYIc");
  I.retry({ retries: 10, minTimeout: 1000 }).fillField('//*[@id="newsletter"]', "1");
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="form-validate"]/div/div[1]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Минимальная длина этого поля');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Please enter the same value again.');
});

Scenario('test search', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.fillField('//*[@id="search"]', 'пылес');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="search_mini_form"]/button');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Результаты поиска');
  I.see('Пылесос Midea');
});

Scenario('test wishlist', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.click('li.authorization-link > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход в систему');
  I.fillField("input[name='login[username]']", "tolik_kos@mail.ru");
  I.fillField("input[name='login[password]']", "feq0ZYIc");
  I.click('//*[@id="send2"]');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Моя панель управления');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="store.menu"]/div/div/nav/ul/li[1]/a[1]');
  I.retry({ retries: 10, minTimeout: 1000 }).click('//*[@id="maincontent"]/div[3]/div[1]/div[4]/ol/li[1]/div/div/div[2]/a/span/span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('div.Product__Actions--Bookmark > div > div > a.action.towishlist');
  I.retry({ retries: 10, minTimeout: 1000 }).see('добавлен в ваш лист пожеланий');
});

Scenario('screenshots', (I) => {
I.amOnPage('https://www.mideastore.ru/');
I.saveScreenshot('MID_main.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_main.png');
I.amOnPage('https://www.mideastore.ru/payment');
I.saveScreenshot('MID_payment.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_payment.png');
I.amOnPage('https://www.mideastore.ru/stockists/');
I.saveScreenshot('MID_stockists.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_stockists.png');
I.amOnPage('https://www.mideastore.ru/about-us');
I.saveScreenshot('MID_about.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_about.png');
I.amOnPage('https://www.mideastore.ru/contacts');
I.saveScreenshot('MID_contacts.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_contacts.png');
I.amOnPage('https://www.mideastore.ru/customer/account/login/');
I.saveScreenshot('MID_login.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_login.png');
I.amOnPage('https://www.mideastore.ru/customer/account/create/');
I.saveScreenshot('MID_registration.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_registration.png');
I.amOnPage('https://www.mideastore.ru/checkout/cart/');
I.saveScreenshot('MID_cart.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_cart.png');
I.amOnPage('https://www.mideastore.ru/blog/');
I.saveScreenshot('MID_blog.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_blog.png');
I.amOnPage('https://www.mideastore.ru/privacy-policy');
I.saveScreenshot('MID_privacy-policy.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_privacy-policy.png');
I.amOnPage('https://www.mideastore.ru/price1');
I.saveScreenshot('MID_dogovor.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_dogovor.png');
I.amOnPage('https://www.mideastore.ru/vstraivaemaja-bytovaja-tehnika.html');
I.saveScreenshot('MID_cataog.png');
I.addMochawesomeContext('/Users/hamster/codecept/mochawesome-report/MID_cataog.png');
});
