
Feature('MID', {retries: 1});

Scenario('test links', (I) => {
  I.amOnPage('https://mideastore.ru');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Войти');
  I.click('li.authorization-link > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Вход в систему');
  I.click('div.top-right.mobile-center > div > div > div > ul > li:nth-child(2) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Создать новую учётную запись клиента');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Встраиваемая Бытовая Техника');
  I.click('nav > ul > li:nth-child(5) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Бесплатная доставка по всей России');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('nav > ul > li:nth-child(6) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Поиск сервисного центра');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('nav > ul > li:nth-child(7) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Midea – мировой производитель бытовой техники');
  I.click('div.place-menu-mobile.menu-mobile > span');
  I.retry({ retries: 10, minTimeout: 1000 }).click('nav > ul > li:nth-child(8) > a');
  I.retry({ retries: 10, minTimeout: 1000 }).see('Midea в Российской Федерации');
  I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/about-us/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Midea – мировой производитель бытовой техники');
        I.retry({ retries: 10, minTimeout: 1000 }).see('О Midea');
        I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/blog/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Последние новости');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Блог');
        I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/contacts/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Midea в Российской Федерации');
        I.retry({ retries: 10, minTimeout: 1000 }).see('ООО "МИДЕА ОНЛАЙН"');
        I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/privacy-policy/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Политика конфиденциальности');
        I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/price1/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Договор оферты');
        I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/stockists/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Поиск сервисного центра');
        I.retry({ retries: 10, minTimeout: 1000 }).click('a[href="/payment/"]');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Бесплатная доставка по всей России');
        I.retry({ retries: 10, minTimeout: 1000 }).see('Midea в России');
});
